apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner-deployment
  namespace: arc-system
spec:
  replicas: 1
  template:
    spec:
      repository: your-org/your-repo
      labels: ["self-hosted", "linux", "x64"]
      containerMode: kubernetes
      resources:
        limits:
          cpu: "2.0"
          memory: "4Gi"
        requests:
          cpu: "1.0"
          memory: "2Gi"
