apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        image: "{{ .Values.controller.repository }}:{{ .Values.controller.tag }}"
        resources:
          {{- toYaml .Values.controller.resources | nindent 12 }}
